src/Entity/Comment.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\JoinColumn;
use Doctrine\ORM\Mapping\ManyToOne;
use Doctrine\ORM\Mapping\OneToMany;

/**
 * @ORM\Table(name="ctg_comments",
 *     indexes={@ORM\Index(name="create_date", columns={"create_date"}),
 *      @ORM\Index(name="md5", columns={"md5"}),
 *      @ORM\Index(name="item_type", columns={"item_type"}),
 *      @ORM\Index(name="id_item_2", columns={"id_item", "id_visitor"}),
 *      @ORM\Index(name="id_visitor", columns={"id_visitor"})})
 * @ORM\Entity
 */
class Comment
{
    /**
     * @var int
     *
     * @ORM\Column(name="id_comment", type="integer", nullable=false)
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Posts", inversedBy="comments")
     * @ORM\JoinColumn(name="id_item", referencedColumnName="id_post")
     */
    private $post;

    /**
     * @var int
     *
     * @ORM\Column(name="item_type", type="integer", nullable=false)
     */
    private $itemType = '0';

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255, nullable=false)
     */
    private $name = '';

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="text", length=255, nullable=false)
     */
    private $email;

    /**
     * @var string|null
     *
     * @ORM\Column(name="comment", type="text", length=65535, nullable=true)
     */
    private $comment;

    /**
     * @var string|null
     *
     * @ORM\Column(name="comment_clear", type="text", length=65535, nullable=true)
     */
    private $commentClear;

    /**
     * @var string
     *
     * @ORM\Column(name="md5", type="string", length=32, nullable=false, options={"fixed"=true})
     */
    private $md5;

    /**
     * @var DateTime
     *
     * @ORM\Column(name="create_date", type="datetime", nullable=false, options={"default"="CURRENT_TIMESTAMP"})
     */
    private $createDate;

    /**
     * @var string
     *
     * @ORM\Column(name="ip", type="string", length=24, nullable=false)
     */
    private $ip = '';

    /**
     * @var string
     *
     * @ORM\Column(name="status", type="string", length=0, nullable=false, options={"default"="WAIT"})
     */
    private $status = 'WAIT';

    /**
     * @var string
     *
     * @ORM\Column(name="status_note", type="string", length=100, nullable=false)
     */
    private $statusNote = '';

    /**
     * @var DateTime
     *
     * @ORM\Column(name="status_change_date", type="datetime", nullable=false, options={"default"="0000-00-00 00:00:00"})
     */
    private $statusChangeDate;

    /**
     * @var string
     *
     * @ORM\Column(name="status_changed_by", type="string", length=30, nullable=false)
     */
    private $statusChangedBy = 'visitor';

    /**
     * @var Visitor|null
     *
     * @ManyToOne(targetEntity="App\Entity\Visitor")
     * @JoinColumn(name="id_visitor", referencedColumnName="id_visitor")
     */
    private $visitor;

    /**
     * @var int
     *
     * @ORM\Column(name="id_citydog", type="integer", nullable=false, options={"unsigned"=true})
     */
    private $idCitydog = 0;

    /**
     * @var Comment|null
     * @ManyToOne(targetEntity="App\Entity\Comment", inversedBy="children")
     * @JoinColumn(name="id_parent", referencedColumnName="id_comment")
    )
     */
    private $parent;

    /**
     * @var ArrayCollection
     * @OneToMany(targetEntity="App\Entity\Comment", mappedBy="parent")
     */
    private $children;

    /**
     * @var int
     *
     * @ORM\Column(name="like_hit", type="integer", nullable=false)
     */
    private $likeHit = 0;

    /**
     * @var int
     *
     * @ORM\Column(name="like_shit", type="integer", nullable=false)
     */
    private $likeShit = 0;

    public function __construct() {
        $this->children = new ArrayCollection();
    }

    /**
     * @return int
     */
    public function getId(): int {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId(int $id): void {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getPost() {
        return $this->post;
    }

    /**
     * @param mixed $post
     */
    public function setPost($post): void {
        $this->post = $post;
    }

    /**
     * @return int
     */
    public function getItemType(): int {
        return $this->itemType;
    }

    /**
     * @param int $itemType
     */
    public function setItemType(int $itemType): void {
        $this->itemType = $itemType;
    }

    /**
     * @return string
     */
    public function getName(): string {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName(string $name): void {
        $this->name = $name;
    }

    /**
     * @return string
     */
    public function getEmail(): string {
        return $this->email;
    }

    /**
     * @param string $email
     */
    public function setEmail(string $email): void {
        $this->email = $email;
    }

    /**
     * @return string|null
     */
    public function getComment(): ?string {
        return $this->comment;
    }

    /**
     * @param string|null $comment
     */
    public function setComment(?string $comment): void {
        $this->comment = $comment;
    }

    /**
     * @return string|null
     */
    public function getCommentClear(): ?string {
        return $this->commentClear;
    }

    /**
     * @param string|null $commentClear
     */
    public function setCommentClear(?string $commentClear): void {
        $this->commentClear = $commentClear;
    }

    /**
     * @return string
     */
    public function getMd5(): string {
        return $this->md5;
    }

    /**
     * @param string $md5
     */
    public function setMd5(string $md5): void {
        $this->md5 = $md5;
    }

    /**
     * @return DateTime
     */
    public function getCreateDate(): DateTime {
        return $this->createDate;
    }

    /**
     * @param DateTime $createDate
     */
    public function setCreateDate(DateTime $createDate): void {
        $this->createDate = $createDate;
    }

    /**
     * @return string
     */
    public function getIp(): string {
        return $this->ip;
    }

    /**
     * @param string $ip
     */
    public function setIp(string $ip): void {
        $this->ip = $ip;
    }

    /**
     * @return string
     */
    public function getStatus(): string {
        return $this->status;
    }

    /**
     * @param string $status
     */
    public function setStatus(string $status): void {
        $this->status = $status;
    }

    /**
     * @return string
     */
    public function getStatusNote(): string {
        return $this->statusNote;
    }

    /**
     * @param string $statusNote
     */
    public function setStatusNote(string $statusNote): void {
        $this->statusNote = $statusNote;
    }

    /**
     * @return DateTime
     */
    public function getStatusChangeDate(): DateTime {
        return $this->statusChangeDate;
    }

    /**
     * @param DateTime $statusChangeDate
     */
    public function setStatusChangeDate(DateTime $statusChangeDate): void {
        $this->statusChangeDate = $statusChangeDate;
    }

    /**
     * @return string
     */
    public function getStatusChangedBy(): string {
        return $this->statusChangedBy;
    }

    /**
     * @param string $statusChangedBy
     */
    public function setStatusChangedBy(string $statusChangedBy): void {
        $this->statusChangedBy = $statusChangedBy;
    }

    /**
     * @return Visitor|null
     */
    public function getVisitor(): ?Visitor {
        return $this->visitor;
    }

    /**
     * @param Visitor|null $visitor
     */
    public function setVisitor(?Visitor $visitor): void {
        $this->visitor = $visitor;
    }

    /**
     * @return int
     */
    public function getIdCitydog(): int {
        return $this->idCitydog;
    }

    /**
     * @param int $idCitydog
     */
    public function setIdCitydog(int $idCitydog): void {
        $this->idCitydog = $idCitydog;
    }

    /**
     * @return Comment|null
     */
    public function getParent(): ?Comment {
        return $this->parent;
    }

    /**
     * @param Comment|null $parent
     */
    public function setParent(?Comment $parent): void {
        $this->parent = $parent;
    }

    /**
     * @return Collection
     */
    public function getChildren(): Collection {
        $criteria = Criteria::create();

        $criteria->where(Criteria::expr()->eq('status', 'APPROVE'));

        return $this->children->matching($criteria);
    }

    /**
     * @param mixed $children
     */
    public function setChildren($children): void {
        $this->children = $children;
    }

    /**
     * @return int
     */
    public function getLikeHit(): int {
        return $this->likeHit;
    }

    /**
     * @param int $likeHit
     */
    public function setLikeHit(int $likeHit): void {
        $this->likeHit = $likeHit;
    }

    /**
     * @return int
     */
    public function getLikeShit(): int {
        return $this->likeShit;
    }

    /**
     * @param int $likeShit
     */
    public function setLikeShit(int $likeShit): void {
        $this->likeShit = $likeShit;
    }

    public function isApproved(): bool {
        return $this->status === 'APPROVE';
    }

    public function setApproved(bool $approved): void {
        if ($approved) {
            $this->status = 'APPROVE';
        } else {
            $this->setStatus('WAIT');
        }
    }

    public function getFullName() {
        if($this->visitor) {
            return $this->visitor->getFullname();
        }

        return $this->getName();
    }

templates/components/article_thumbnail.html.twig
<div>
    {# @var post App\Entity\Posts #}
    <a href="{{ path('article_detail', {'url': post.url}) }}"><div style="background-image: url('{{vich_uploader_asset(post, 'imageFile')}}')" class="mb-2 article-thumbnail"></div></a>
    <a href="{{ path('article_detail', {'url': post.url}) }}"><h3 class="text-dark font-weight-medium" style="font-size: 18px;">
            {{post.postTitle|raw}}
        </h3></a>
    <p>{{ post.summary }}…</p>

</div>

templates/components/breadcrumb_navigation.html.twig
<nav aria-label="breadcrumb" class="breadcrumb-nav">
            <ol class="breadcrumb bg-white" style="font-size: 12px;">
                {% for item in breadcrumbs %}
                    <li class="breadcrumb-item {% if loop.last  %}active{% endif %}"><a class="text-uppercase text-light" href="{{ item['link'] }}">{{ item['name'] }}</a></li>
                {% endfor %}
            </ol>
          </nav>

templates/components/comment.html.twig
<div class="commnent" id="comment_{{ comment.id }}">
    <div class="comment-body mt-4 d-flex flex-md-row flex-column">
        <div class="d-flex align-items-center align-items-md-start pb-2">
            <div class="comment-avatar mr-3 mx-md-3" style="background-image: url('/images/png/avatar_def.png')">
            </div>
            <div class="pb-2 d-block d-md-none">
                <div class="font-weight-bold comment-author">
                    {{ comment.name }}
                </div>
                <div class="fs-12 text-muted"><span class="date">{{ comment.createDate|date('d.m.Y') }}</span> <span
                            class="time">{{ comment.createDate|date('H:i') }}</span></div>
            </div>
        </div>
        <div class="flex-grow-1">
            <div class="pb-2 d-none d-md-block">
                <div class="font-weight-bold comment-author">
                    {{ comment.fullName }}
                </div>
                <div class="fs-12 text-muted"><span class="date">20.02</span> <span class="time">09:20</span></div>
            </div>
            <div class="">{{ comment.commentClear|raw }}</div>
            <div class="fs-12 d-flex justify-content-end mt-2">
                <a class="answer-comment-a" data-reply-to-id="{{ comment.id }}" data-reply-to-name="{{ comment.name }}"
                   href="#commentForm">ODPOVĚDĚT</a>
            </div>
            {% if not comment.parent  and comment.children.count > 0 %}
            <div class="fs-12 d-flex">
                <a class="answer-comment-a" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="collapseRepliess"
                   href="#collapseReplies{{ comment.id }}">zobrazit {{ comment.children.count }} odpovědí</a>
            </div>
            {% endif %}
        </div>
    </div>
    <div class="{{ (comment.parent == null) ? 'collapse' : '' }}" id="collapseReplies{{ comment.id }}">
    {% for response in comment.children %}
        <div class="comment-response ml-4">
            {% include 'components/comment.html.twig' with {'comment': response} %}
        </div>
    {% endfor %}
    </div>
</div>

templates/components/cookies_popup.html.twig
<div class="cookies-popup d-none d-sm-block" id="cookiesPopup">
    <div class="container">
        <div>
            Při poskytování služeb nám pomáhají soubory cookie. Používáním našich služeb vyjadřujete souhlas s naším
            používáním souborů cookie.
            <a class="text-underlined text-dark text-nowrap" href="{{ path('privacy') }}">Další informace</a></div>
        <a href="" id="closeCookiesPopup"><img src="/images/svg/popup_close_icon.svg" alt="popupClose"></a>
    </div>
</div>

templates/components/main_article_thumbnail.html.twig
<div class="my-3">
    <div class="position-relative main-article-thumbnail"
         style="background-image: url('{{ vich_uploader_asset(post, 'imageFile') }}');">
        <div class="image-overlay d-flex">
            <div class="main-article-link-wrapper m-auto w-75 align-self-center">
                <h2 class="text-center">
                    <a class="main-article-link"
                       href="{{ path('article_detail', {'url': post.url}) }}">{{ post.postTitle|raw }}</a>
                </h2>
            </div>
            {% if post.gallery %}
                <a href="{{ path('gallery', {'url': post.url}) }}"
                   class="mx-1 btn main-btn gallery-btn text-uppercase rounded-0 d-md-block d-none overlay-gallery-button">galerie
                    ({{ post.galleryImageCount }})<img class="ml-2" src="/images/svg/Next_photos.svg" alt="Next_photos"></a>
            {% endif %}
        </div>
    </div>
    <div class="d-flex d-md-none align-items-center my-2">
        {% if post.gallery %}
            {% for image in post.images|slice(0,2) %}
                <a class="mr-2 {% if loop.index == 2 %}d-none d-sm-block{% endif %}" href="{{ path('gallery', {'url': post.url}) }}">
                    <div class="small-gallery-thumbnail"
                         style="background-image: url('{{ vich_uploader_asset(image, 'imageFile') }}')"></div>
                </a>
            {% endfor %}
            <a href="{{ path('gallery', {'url': post.url}) }}" class="mx-1 btn main-btn gallery-btn text-uppercase rounded-0">galerie
                ({{ post.getGalleryImageCount }})<img class="ml-2" src="/images/svg/Next_photos.svg" alt="Next_photos"></a>
        {% endif %}
    </div>
</div>

templates/components/paginator.html.twig
<nav class="my-5">
    {% set polomer = 3 %}
    {% set left = actualPage - polomer >= 1 ? actualPage - polomer : 1 %}
    {% set right = actualPage + polomer <= pages ? actualPage + polomer : pages %}
    {% if category is not defined %}
        {% set category = 0 %}
    {% endif %}
    <ul class="pagination justify-content-center align-items-center">
        {% if actualPage > 1 %}
            <li class="page-item  arrow">
                <a class="page-link" style="transform: rotate(180deg);"
                   href="{{ path(path, { 'page' : actualPage-1, 'category': category}) }}">
                    <img src="/images/svg/arrow_right_black.svg" alt="arrow_right_black">
                </a>
            </li>
        {% endif %}
        {% if left > 1 %}
            ...
        {% endif %}
        {% if pages > 1 %}
            {% for page in left..right %}
                <li class="page-item num-page-button {% if page == actualPage %}active{% endif %}"><a
                            class="page-link" href="{{ path(path, {'page': page, 'category': category}) }}">{{ page }}</a>
                </li>
            {% endfor %}
        {% endif %}
        {% if right < pages - 1 %}
            ...
        {% endif %}
        {% if pages > 1 %}
            <li class="page-item arrow">
                <a class="page-link" href="{{ path(path, { 'page' : actualPage+1, 'category': category}) }}">
                    <img src="/images/svg/arrow_right_black.svg" alt="arrow_right_black">
                </a>
            </li>
        {% endif %}
    </ul>
</nav>

templates/components/search_result_item.html.twig
<div class="col-12 col-sm-6 col-md-10 col-lg-7 offset-md-1">
    <div class="d-flex flex-column flex-md-row">
        <div class="small-gallery-thumbnail mr-3 flex-shrink-0 mb-2"
             style="background-image: url('{{ vich_uploader_asset(post, 'imageFile') }}')"></div>
        <div>
            <a href="{{ path('article_detail', {'url': post.url}) }}"><h3 class="text-dark fs-18">{{ post.postTitle }}</h3></a>
            <p>{{ post.summary }}</p>
        </div>

    </div>
</div>

templates/components/support_popup.html.twig
<div class="position-fixed support-popup-wrapper align-items-center" id="supportPopup">
    <div class="container support-popup position-relative">
        <div class="row">
            <div class="col-md-6 col-lg-5 offset-lg-1">
                <img src="/images/svg/heart.svg" class="d-block my-3" alt="heart">
                <h3 class="text-white">Líbí se vám náš obsah?<br>
                    <span class="text-underlined">Podpořte nás!</span></h3>
                <p class="fs-18 text-white">Jsme nezávislé médium bez velkých investorů či zahraničních vlastníků. Proto
                    budeme
                    rádi, pokud nám projevíte svou přízeň prostřednictvím malého příspěvku. Děkujeme!</p>
            </div>
            <div class="col-md-6 col-lg-5 d-flex flex-column justify-content-center align-items-center">
                <div class="fs-20 pb-2">Podpořte nás a pošlete nám:</div>
                <div class="d-flex">
                    <div class="mx-3 d-flex flex-column">
                        <img src="/images/svg/20crowns.svg" alt="20crowns">
                        <a href="{{ path('support', {'castka': 20}) }}" class="btn btn-outline-secondary rounded-0 border-width-2 p-0 my-2 fs-20 text-center">20 Kč</a>
                    </div>
                    <div class="mx-3 d-flex flex-column">
                        <img src="/images/svg/50crowns.svg" alt="50crowns">
                        <a href="{{ path('support', {'castka': 50}) }}" class="btn btn-outline-secondary rounded-0 border-width-2 p-0 my-2 fs-20 text-center">50 Kč</a>
                    </div>
                    <div class="mx-3 d-flex flex-column">
                        <img src="/images/svg/100crowns.svg" alt="100crowns">
                        <a href="{{ path('support', {'castka': 100}) }}" class="btn btn-outline-secondary rounded-0 border-width-2 p-0 my-2 fs-20 text-center">100 Kč</a>
                    </div>
                </div>
            </div>
            <a class="close-popup fs-12" href="" id="closePopup">Zavřít nemám zájem <img class="ml-2" src="/images/svg/popup_close_icon.svg" alt="close"></a>
        </div>
    </div>
</div>